#pragma once

// Fortnite (3.1) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_E9AC643D4F8E10A8DA0B55AAC496A021
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_E9AC643D4F8E10A8DA0B55AAC496A021_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_31B85E65417FD5B749A7D1941CE581F2
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_31B85E65417FD5B749A7D1941CE581F2_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_2396020B435F19A36A0A74B66AEF983F
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_2396020B435F19A36A0A74B66AEF983F_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_E53448EF44FAA6932E61C5AB75F0A934
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_E53448EF44FAA6932E61C5AB75F0A934_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_CDFFEF5745992E802E51E7B988C735E9
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_CDFFEF5745992E802E51E7B988C735E9_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_245B08CA475D77EAA94BC791564F1191
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_245B08CA475D77EAA94BC791564F1191_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_8AC200CC47265449E4F29B87E0E6813A
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_8AC200CC47265449E4F29B87E0E6813A_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByEnum_BA77578B4776A584119097BD7AF60F6A
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByEnum_BA77578B4776A584119097BD7AF60F6A_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_DBFF2A3D4873EADCFC4B20A49F6AD788
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_DBFF2A3D4873EADCFC4B20A49F6AD788_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_57BDF19A4F945C97D596E7B9283B1FE0
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendSpacePlayer_57BDF19A4F945C97D596E7B9283B1FE0_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_99A7CC204C2BC62DDC7648B22CEF2CC9
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_99A7CC204C2BC62DDC7648B22CEF2CC9_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_9C4B3BDD4AFC09C5F081429CB94C1218
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_9C4B3BDD4AFC09C5F081429CB94C1218_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_8AFC253A4FA076FED632509B05A08B1F
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_8AFC253A4FA076FED632509B05A08B1F_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_423BB37F40D8138856C4A6A2FCB47BF5
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_423BB37F40D8138856C4A6A2FCB47BF5_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_F4C95533411A95A9F762BB9FD76A53F4
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_F4C95533411A95A9F762BB9FD76A53F4_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_0A47267A49936464E45E1394F3DFAB0B
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_0A47267A49936464E45E1394F3DFAB0B_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_F870855E42358A3AE9FFCEA8148515CF
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_F870855E42358A3AE9FFCEA8148515CF_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_2124E040464EE301C3806EB6310AA731
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_BlendListByBool_2124E040464EE301C3806EB6310AA731_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_LayeredBoneBlend_BCA9A2E04E0B18A136F136A5568421AD
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_LayeredBoneBlend_BCA9A2E04E0B18A136F136A5568421AD_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TwoBoneIK_60EFAEA943B8F364186B499519B5FD1B
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TwoBoneIK_60EFAEA943B8F364186B499519B5FD1B_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TwoBoneIK_4F6075D44B5DB20527031CA1AF9B0E10
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TwoBoneIK_4F6075D44B5DB20527031CA1AF9B0E10_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_D459C88940BDBABEB803EC8C749D6A1D
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_D459C88940BDBABEB803EC8C749D6A1D_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_FAEC6E854E39405FA5831D8F5A110DFF
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_FAEC6E854E39405FA5831D8F5A110DFF_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.BlueprintUpdateAnimation
struct UMaleSurvivorAnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.BlueprintInitializeAnimation
struct UMaleSurvivorAnimBlueprint_C_BlueprintInitializeAnimation_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.AnimNotify_SurvivorIdleDefaultEnded
struct UMaleSurvivorAnimBlueprint_C_AnimNotify_SurvivorIdleDefaultEnded_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.AnimNotify_SurvivorIdleCowerEnded
struct UMaleSurvivorAnimBlueprint_C_AnimNotify_SurvivorIdleCowerEnded_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.AnimNotify_SurvivorIdleCowerBreakEnded
struct UMaleSurvivorAnimBlueprint_C_AnimNotify_SurvivorIdleCowerBreakEnded_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.AnimNotify_SurvivorIdleDefaultBreakEnded
struct UMaleSurvivorAnimBlueprint_C_AnimNotify_SurvivorIdleDefaultBreakEnded_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_DC38DF88419C50A445BC738043D38E33
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_DC38DF88419C50A445BC738043D38E33_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.AnimNotify_MedBot_Revive_Done
struct UMaleSurvivorAnimBlueprint_C_AnimNotify_MedBot_Revive_Done_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_897CDDDF48EACA4D93120F9D029B71E7
struct UMaleSurvivorAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_MaleSurvivorAnimBlueprint_AnimGraphNode_TransitionResult_897CDDDF48EACA4D93120F9D029B71E7_Params
{
};

// Function MaleSurvivorAnimBlueprint.MaleSurvivorAnimBlueprint_C.ExecuteUbergraph_MaleSurvivorAnimBlueprint
struct UMaleSurvivorAnimBlueprint_C_ExecuteUbergraph_MaleSurvivorAnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
